version: "3.8"

services:
  qwirkle-app:
    image: nginx:alpine
    ports:
      - "9080:80"
    container_name: qwirkle-score-tracker
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./dist:/usr/share/nginx/html/dist:ro
